version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: ifsc-mysql
    command: --bind-address=0.0.0.0 --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ifsc_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ifsc-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: ifsc-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ifsc-network
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: ifsc-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=ifsc_db
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - IFSC_FRESHNESS_DAYS=7
      - CACHE_TTL_SECONDS=300
      - EXTERNAL_API_BASE_URL=https://ifsc.razorpay.com
    depends_on:
      - mysql
      - redis
    networks:
      - ifsc-network
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: ifsc-frontend
    ports:
      - "80:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:3000/api
    depends_on:
      - backend
    networks:
      - ifsc-network
    restart: unless-stopped

volumes:
  mysql_data:
  redis_data:

networks:
  ifsc-network: